In [89]:
#!apt install libomp-dev
#!python -m pip install --upgrade faiss faiss-gpu
import faiss

In [90]:
import numpy as np
import faiss 
import time

In [91]:
import pandas as pd

In [92]:
from numpy.linalg import norm
import pickle
from tqdm import tqdm, tqdm_notebook
import os
import time
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import ResNet50, preprocess_input

In [95]:
model = ResNet50(weights='imagenet', include_top=False,
                 input_shape=(224, 224, 3))

model = ResNet50(weights='imagenet', include_top=False,
                 input_shape=(180, 180, 3))
def extract_features(img_path, model):
    input_shape = (180, 180, 3)
    img = image.load_img(img_path, target_size=(
        input_shape[0], input_shape[1]))
    img_array = image.img_to_array(img)
    expanded_img_array = np.expand_dims(img_array, axis=0)
    preprocessed_img = preprocess_input(expanded_img_array)
    features = model.predict(preprocessed_img)
    flattened_features = features.flatten()
    normalized_features = flattened_features / norm(flattened_features)
    return normalized_features

In [96]:
extensions = ['.jpg', '.JPG', '.jpeg', '.JPEG', '.png', '.PNG']
def get_file_list(root_dir):
    file_list = []
    counter = 1
    for root, directories, filenames in os.walk(root_dir):
        for filename in filenames:
            if any(ext in filename for ext in extensions):
                file_list.append(os.path.join(root, filename))
                counter += 1
    return file_list

In [99]:
root_dir = '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass'
filenames = sorted(get_file_list(root_dir))

In [102]:
feature_list = []
for i in tqdm(range(len(filenames))):
    feature_list.append(extract_features(filenames[i], model))




  0%|          | 0/522 [00:00<?, ?it/s]Exception ignored in: <function tqdm.__del__ at 0x7ffb7586e700>
Traceback (most recent call last):
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/std.py", line 1147, in __del__
    self.last_print_n = last_print_n
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/notebook.py", line 286, in close
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/notebook.py", line 160, in display
    right = right[1:]
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/std.py", line 1461, in format_dict
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/notebook.py", line 203, in colour
    unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
AttributeError: 'FloatProgress' object has no attribute 'style'
Exception ignored in: <function tqdm.__del__ at 0x7ffb7586e700>
Traceback (most recent call last):
  File "/home/sanket/.local/lib/python3.8/site-packages/tqdm/std.py", line 1147, in __del__


 19%|█▉        | 98/522 [00:18<01:09,  6.09it/s]


 19%|█▉        | 99/522 [00:18<01:08,  6.18it/s]


 19%|█▉        | 100/522 [00:18<01:06,  6.33it/s]


 19%|█▉        | 101/522 [00:18<01:04,  6.52it/s]


 20%|█▉        | 102/522 [00:18<01:02,  6.68it/s]


 20%|█▉        | 103/522 [00:19<01:01,  6.79it/s]


 20%|█▉        | 104/522 [00:19<01:02,  6.68it/s]


 20%|██        | 105/522 [00:19<01:03,  6.59it/s]


 20%|██        | 106/522 [00:19<01:04,  6.44it/s]


 20%|██        | 107/522 [00:19<01:04,  6.39it/s]


 21%|██        | 108/522 [00:19<01:03,  6.52it/s]


 21%|██        | 109/522 [00:19<01:02,  6.57it/s]


 21%|██        | 110/522 [00:20<01:02,  6.57it/s]


 21%|██▏       | 111/522 [00:20<01:02,  6.58it/s]


 21%|██▏       | 112/522 [00:20<01:02,  6.53it/s]


 22%|██▏       | 113/522 [00:20<01:08,  5.99it/s]


 22%|██▏       | 114/522 [00:20<01:05,  6.19it/s]


 22%|██▏       | 115/522 [00:20<01:04,  6.26it/s]


 22%|██▏       | 116/522 [00:21<01:04,  6.33it/s]


 22%|██▏      

 44%|████▍     | 232/522 [00:40<00:50,  5.69it/s]


 45%|████▍     | 233/522 [00:41<00:52,  5.54it/s]


 45%|████▍     | 234/522 [00:41<00:51,  5.60it/s]


 45%|████▌     | 235/522 [00:41<00:49,  5.75it/s]


 45%|████▌     | 236/522 [00:41<00:47,  5.98it/s]


 45%|████▌     | 237/522 [00:41<00:47,  5.97it/s]


 46%|████▌     | 238/522 [00:42<00:47,  5.98it/s]


 46%|████▌     | 239/522 [00:42<00:51,  5.51it/s]


 46%|████▌     | 240/522 [00:42<00:51,  5.45it/s]


 46%|████▌     | 241/522 [00:42<00:51,  5.50it/s]


 46%|████▋     | 242/522 [00:42<00:55,  5.03it/s]


 47%|████▋     | 243/522 [00:42<00:52,  5.29it/s]


 47%|████▋     | 244/522 [00:43<00:55,  5.01it/s]


 47%|████▋     | 245/522 [00:43<00:53,  5.20it/s]


 47%|████▋     | 246/522 [00:43<00:54,  5.03it/s]


 47%|████▋     | 247/522 [00:43<00:53,  5.16it/s]


 48%|████▊     | 248/522 [00:43<00:51,  5.35it/s]


 48%|████▊     | 249/522 [00:44<00:54,  5.03it/s]


 48%|████▊     | 250/522 [00:44<00:50,  5.39it/s]


 48%|████▊  

 70%|███████   | 366/522 [01:06<00:25,  6.06it/s]


 70%|███████   | 367/522 [01:06<00:25,  6.01it/s]


 70%|███████   | 368/522 [01:06<00:25,  6.02it/s]


 71%|███████   | 369/522 [01:06<00:25,  6.11it/s]


 71%|███████   | 370/522 [01:06<00:25,  6.06it/s]


 71%|███████   | 371/522 [01:06<00:24,  6.26it/s]


 71%|███████▏  | 372/522 [01:07<00:24,  6.02it/s]


 71%|███████▏  | 373/522 [01:07<00:24,  6.11it/s]


 72%|███████▏  | 374/522 [01:07<00:24,  6.12it/s]


 72%|███████▏  | 375/522 [01:07<00:23,  6.23it/s]


 72%|███████▏  | 376/522 [01:07<00:23,  6.23it/s]


 72%|███████▏  | 377/522 [01:07<00:24,  5.81it/s]


 72%|███████▏  | 378/522 [01:08<00:27,  5.15it/s]


 73%|███████▎  | 379/522 [01:08<00:32,  4.44it/s]


 73%|███████▎  | 380/522 [01:08<00:29,  4.87it/s]


 73%|███████▎  | 381/522 [01:08<00:28,  4.97it/s]


 73%|███████▎  | 382/522 [01:09<00:31,  4.51it/s]


 73%|███████▎  | 383/522 [01:09<00:27,  4.99it/s]


 74%|███████▎  | 384/522 [01:09<00:31,  4.40it/s]


 74%|███████

 96%|█████████▌| 500/522 [01:31<00:03,  5.77it/s]


 96%|█████████▌| 501/522 [01:31<00:03,  5.62it/s]


 96%|█████████▌| 502/522 [01:31<00:03,  5.70it/s]


 96%|█████████▋| 503/522 [01:31<00:03,  5.52it/s]


 97%|█████████▋| 504/522 [01:32<00:03,  5.60it/s]


 97%|█████████▋| 505/522 [01:32<00:02,  5.75it/s]


 97%|█████████▋| 506/522 [01:32<00:02,  5.60it/s]


 97%|█████████▋| 507/522 [01:32<00:02,  5.58it/s]


 97%|█████████▋| 508/522 [01:32<00:02,  5.73it/s]


 98%|█████████▊| 509/522 [01:32<00:02,  5.72it/s]


 98%|█████████▊| 510/522 [01:33<00:02,  5.97it/s]


 98%|█████████▊| 511/522 [01:33<00:01,  6.09it/s]


 98%|█████████▊| 512/522 [01:33<00:01,  5.66it/s]


 98%|█████████▊| 513/522 [01:33<00:01,  5.74it/s]


 98%|█████████▊| 514/522 [01:33<00:01,  5.88it/s]


 99%|█████████▊| 515/522 [01:33<00:01,  6.08it/s]


 99%|█████████▉| 516/522 [01:34<00:00,  6.04it/s]/usr/lib/python3/dist-packages/PIL/Image.py:931: UserWarning: Palette images with Transparency expressed in bytes shoul

In [103]:
len(filenames)

522

In [104]:
feature_list

[array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.01280678], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.00482241, 0.        ,
        0.        ], dtype=float32),
 array([0.        , 0.00420165, 0.        , ..., 0.        , 0.        ,
        0.00325058], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.        , 0.00932041, 0.        , ..., 0.0038727 , 0.        ,
        0.        ], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.00368807, 0.        ,
        0.        ], dtype=float32),
 array([0.00182746, 0.        , 0.        , ..., 0.00523753, 0.        ,
        0.        ], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00573036], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.00261527, 0.     

In [105]:
feature_list=np.array(feature_list)

In [106]:
type(feature_list)

numpy.ndarray

In [107]:
feature_list.shape

(522, 73728)

In [108]:
dimension = 73728    # dimensions of each vector                         
n = len(filenames)    # number of vectors                   
np.random.seed(1)             
db_vectors = feature_list #np.random.random((n, dimension)).astype('float32')

In [109]:
db_vectors.shape

(522, 73728)

In [110]:
nlist = 1  # number of clusters
quantiser = faiss.IndexFlatL2(dimension)  
index = faiss.IndexIVFFlat(quantiser, dimension, nlist,   faiss.METRIC_L2)

In [111]:
print(index.is_trained)   # False
index.train(db_vectors)  # train on the database vectors
print(index.ntotal)   # 0
index.add(db_vectors)   # add the vectors and update the index
print(index.is_trained)  # True
print(index.ntotal)  

False
0
True
522


In [113]:
nprobe = 1  # find 2 most similar clusters
n_query = 417  
k = 10  # return 3 nearest neighbours
np.random.seed(0)   
query_vectors = feature_list#np.random.random((n_query, dimension)).astype('float32')
distances, indices = index.search(query_vectors, k)

In [114]:
distances

array([[0.        , 1.2098992 , 1.2194543 , ..., 1.2600329 , 1.2779169 ,
        1.2793769 ],
       [0.        , 0.9536538 , 1.012756  , ..., 1.1291883 , 1.1348783 ,
        1.1374547 ],
       [0.        , 0.96946114, 1.048513  , ..., 1.1566718 , 1.1653174 ,
        1.1671937 ],
       ...,
       [0.        , 0.8742478 , 0.91125065, ..., 0.96532357, 1.0024184 ,
        1.0157562 ],
       [0.        , 0.        , 0.50885314, ..., 1.6154395 , 1.6212909 ,
        1.6214998 ],
       [0.        , 0.        , 0.50885314, ..., 1.5284587 , 1.5614756 ,
        1.5652138 ]], dtype=float32)

In [115]:
indices

array([[  0, 325, 485, ..., 146, 257, 489],
       [  1,  56, 115, ..., 418, 138, 272],
       [  2, 146, 485, ..., 226, 220, 157],
       ...,
       [519, 509, 511, ..., 516, 513, 515],
       [520, 502, 503, ..., 515, 507, 505],
       [503, 521, 502, ..., 507,  39, 357]])

In [116]:
faiss.write_index(index,"vectors.index")  # save the index to 
# diskindex = faiss.read_index("vector.index")  # load the index 

In [117]:
diskindex = faiss.read_index("vectors.index")


In [118]:
pickle.dump(feature_list, open('features-cdiscount-resnet.pickle', 'wb'))
pickle.dump(filenames, open('filenames-cdiscount.pickle','wb'))

In [121]:
files = pickle.load(open('filenames-cdiscount.pickle', 'rb'))
feature_list = pickle.load(open('features-cdiscount-resnet.pickle', 'rb'))

In [122]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [123]:
files[1]

'/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/1.jpg'

In [124]:
files

['/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/0.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/1.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/10.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/100.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/101.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/102.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/103.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/104.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/105.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/106.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/107.jpg',
 '/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/108.jpg',
 '/media/sanket/SSD_Windows/Users

In [127]:
filenamenew = [i.split('/media/sanket/SSD_Windows/Users/Owner/adm/Fashion_Dataset/test/fiass/')[1] for i in files]

In [128]:
filenamenew

['0.jpg',
 '1.jpg',
 '10.jpg',
 '100.jpg',
 '101.jpg',
 '102.jpg',
 '103.jpg',
 '104.jpg',
 '105.jpg',
 '106.jpg',
 '107.jpg',
 '108.jpg',
 '109.jpg',
 '11.jpg',
 '110.jpg',
 '111.jpg',
 '112.jpg',
 '113.jpg',
 '114.jpg',
 '115.jpg',
 '116.jpg',
 '117.jpg',
 '118.jpg',
 '119.jpg',
 '12.jpg',
 '120.jpg',
 '121.jpg',
 '122.jpg',
 '123.jpg',
 '124.jpg',
 '125.jpg',
 '126.jpg',
 '127.jpg',
 '128.jpg',
 '129.jpg',
 '13.jpg',
 '130.jpg',
 '131.jpg',
 '132.jpg',
 '133.jpg',
 '134.jpg',
 '135.jpg',
 '136.jpg',
 '137.jpg',
 '138.jpg',
 '139.jpg',
 '14.jpg',
 '140.jpg',
 '141.jpg',
 '142.jpg',
 '143.jpg',
 '144.jpg',
 '145.jpg',
 '146.jpg',
 '147.jpg',
 '148.jpg',
 '149.jpg',
 '15.jpg',
 '150.jpg',
 '151.jpg',
 '152.jpg',
 '153.jpg',
 '154.jpg',
 '155.jpg',
 '156.jpg',
 '157.jpg',
 '158.jpg',
 '159.jpg',
 '16.jpg',
 '160.jpg',
 '161.jpg',
 '162.jpg',
 '163.jpg',
 '164.jpg',
 '165.jpg',
 '166.jpg',
 '167.jpg',
 '168.jpg',
 '169.jpg',
 '17.jpg',
 '170.jpg',
 '171.jpg',
 '172.jpg',
 '173.jpg',
 '17

In [129]:
index = []
for i in range(len(filenamenew)):
  index.append(i)

In [130]:
index

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [131]:
df = pd.DataFrame()
# df['index'] = index
df['images'] = filenamenew

In [132]:
df

images
0                                                0.jpg
1                                                1.jpg
2                                               10.jpg
3                                              100.jpg
4                                              101.jpg
..                                                 ...
517  lib/python3.8/site-packages/notebook/static/co...
518  lib/python3.8/site-packages/notebook/static/co...
519  lib/python3.8/site-packages/notebook/static/co...
520       share/jupyter/kernels/python3/logo-32x32.png
521       share/jupyter/kernels/python3/logo-64x64.png

[522 rows x 1 columns]

In [133]:
indi_df = pd.DataFrame(indices)
indi_df

0    1    2    3    4    5    6    7    8    9
0      0  325  485  370  379   79  184  146  257  489
1      1   56  115  203    8  123  433  418  138  272
2      2  146  485   79  224   57  222  226  220  157
3      3   64  156  308  304  212  340  154  197  130
4      4  426  141  131  152  217  170  361  345  194
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
517  517  515  518  500  501  516  509  511  510  512
518  518  501  500  517  515  516  509  511  510  514
519  519  509  511  514  510  512  517  516  513  515
520  520  502  503  521  504  508  519  515  507  505
521  503  521  502  520  504  505  508  507   39  357

[522 rows x 10 columns]

In [134]:
dfnew = df.to_dict()
dfnew = dfnew['images']

In [135]:
dfnew

{0: '0.jpg',
 1: '1.jpg',
 2: '10.jpg',
 3: '100.jpg',
 4: '101.jpg',
 5: '102.jpg',
 6: '103.jpg',
 7: '104.jpg',
 8: '105.jpg',
 9: '106.jpg',
 10: '107.jpg',
 11: '108.jpg',
 12: '109.jpg',
 13: '11.jpg',
 14: '110.jpg',
 15: '111.jpg',
 16: '112.jpg',
 17: '113.jpg',
 18: '114.jpg',
 19: '115.jpg',
 20: '116.jpg',
 21: '117.jpg',
 22: '118.jpg',
 23: '119.jpg',
 24: '12.jpg',
 25: '120.jpg',
 26: '121.jpg',
 27: '122.jpg',
 28: '123.jpg',
 29: '124.jpg',
 30: '125.jpg',
 31: '126.jpg',
 32: '127.jpg',
 33: '128.jpg',
 34: '129.jpg',
 35: '13.jpg',
 36: '130.jpg',
 37: '131.jpg',
 38: '132.jpg',
 39: '133.jpg',
 40: '134.jpg',
 41: '135.jpg',
 42: '136.jpg',
 43: '137.jpg',
 44: '138.jpg',
 45: '139.jpg',
 46: '14.jpg',
 47: '140.jpg',
 48: '141.jpg',
 49: '142.jpg',
 50: '143.jpg',
 51: '144.jpg',
 52: '145.jpg',
 53: '146.jpg',
 54: '147.jpg',
 55: '148.jpg',
 56: '149.jpg',
 57: '15.jpg',
 58: '150.jpg',
 59: '151.jpg',
 60: '152.jpg',
 61: '153.jpg',
 62: '154.jpg',
 63: '155.jp

In [136]:
indi_df

0    1    2    3    4    5    6    7    8    9
0      0  325  485  370  379   79  184  146  257  489
1      1   56  115  203    8  123  433  418  138  272
2      2  146  485   79  224   57  222  226  220  157
3      3   64  156  308  304  212  340  154  197  130
4      4  426  141  131  152  217  170  361  345  194
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
517  517  515  518  500  501  516  509  511  510  512
518  518  501  500  517  515  516  509  511  510  514
519  519  509  511  514  510  512  517  516  513  515
520  520  502  503  521  504  508  519  515  507  505
521  503  521  502  520  504  505  508  507   39  357

[522 rows x 10 columns]

In [137]:
indi_df = indi_df.replace(dfnew)
indi_df

0  \
0                                                0.jpg   
1                                                1.jpg   
2                                               10.jpg   
3                                              100.jpg   
4                                              101.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/notebook/static/co...   
518  lib/python3.8/site-packages/notebook/static/co...   
519  lib/python3.8/site-packages/notebook/static/co...   
520       share/jupyter/kernels/python3/logo-32x32.png   
521  lib/python3.8/site-packages/ipykernel/resource...   

                                                     1  \
0                                              391.jpg   
1                                              149.jpg   
2                                               23.jpg   
3                                              156.jpg   
4                                              482.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/notebook/static/co...   
518  lib/python3.8/site-packages/IPython/core/tests...   
519  lib/python3.8/site-packages/notebook/static/co...   
520  lib/python3.8/site-packages/ipykernel/resource...   
521       share/jupyter/kernels/python3/logo-64x64.png   

                                                     2  \
0                                               86.jpg   
1                                              201.jpg   
2                                               86.jpg   
3                                              239.jpg   
4                                              225.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/notebook/static/co...   
518  lib/python3.8/site-packages/IPython/core/tests...   
519  lib/python3.8/site-packages/notebook/static/co...   
520  lib/python3.8/site-packages/ipykernel/resource...   
521  lib/python3.8/site-packages/ipykernel/resource...   

                                                     3  \
0                                              431.jpg   
1                                              281.jpg   
2                                               17.jpg   
3                                              376.jpg   
4                                              216.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/IPython/core/tests...   
518  lib/python3.8/site-packages/notebook/static/co...   
519  lib/python3.8/site-packages/notebook/static/co...   
520       share/jupyter/kernels/python3/logo-64x64.png   
521       share/jupyter/kernels/python3/logo-32x32.png   

                                                     4  \
0                                               44.jpg   
1                                              105.jpg   
2                                               30.jpg   
3                                              372.jpg   
4                                              235.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/IPython/core/tests...   
518  lib/python3.8/site-packages/notebook/static/co...   
519  lib/python3.8/site-packages/notebook/static/co...   
520  lib/python3.8/site-packages/ipywidgets/widgets...   
521  lib/python3.8/site-packages/ipywidgets/widgets...   

                                                     5  \
0                                               17.jpg   
1                                              209.jpg   
2                                               15.jpg   
3                                               29.jpg   
4                                              294.jpg   
..                                                 ...   
517  lib/python3.8/site-packages/notebook/static/co...   
518  lib/python3.8/site-packages/notebook/static/co...   
519  lib/python3.8/site-packages/notebook/stat

In [138]:
indi_df.to_csv('faiss.csv')